/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import static swing.windows.f;
import classe.DAO.MedicamentDAO;
import medecin.metier.Medicament;
import myconnections.DBConnection;
import java.sql.*;
import javax.swing.JOptionPane;
import java.io.File;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

/**
 *
 * @author jerom
 */
public class Creamedoc extends javax.swing.JPanel {

    /**
     * Creates new form creamed
     */
    
    String nom,desc,code = "";
    Statement stmt;
    ResultSet rs = null;
    Medicament medoc;
    int id;
    
    public Creamedoc() {
        initComponents();
    }
    
    static void PlaySound(File Sound){
        try{
            Clip clip = AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(Sound));
            clip.start();
            
            Thread.sleep(clip.getMicrosecondLength()/1000);
        }catch(Exception e){
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaDesc = new javax.swing.JTextArea();
        btValider = new javax.swing.JButton();
        btAnnuler = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 153));
        setLayout(new java.awt.GridLayout(5, 2, 10, 10));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabel1.setText("Création de médicament");
        add(jLabel1);
        add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Nom");
        add(jLabel3);

        txtNom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtNom);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Code");
        add(jLabel4);

        txtCode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtCode);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Description");
        add(jLabel5);

        txtaDesc.setColumns(20);
        txtaDesc.setRows(5);
        jScrollPane1.setViewportView(txtaDesc);

        add(jScrollPane1);

        btValider.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btValider.setText("Valider");
        btValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btValiderActionPerformed(evt);
            }
        });
        add(btValider);

        btAnnuler.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btAnnuler.setText("Annuler");
        btAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnnulerActionPerformed(evt);
            }
        });
        add(btAnnuler);
    }// </editor-fold>//GEN-END:initComponents

    private void btAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnnulerActionPerformed

        f.setContentPane(new menumedoc());
        f.repaint();
        f.revalidate();
    }//GEN-LAST:event_btAnnulerActionPerformed

    private void btValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btValiderActionPerformed
            MedicamentDAO mdao = new MedicamentDAO();        
            nom=txtNom.getText();
            code=txtCode.getText();
            desc=txtaDesc.getText();
            id=0;
            medoc = new Medicament(id,nom,desc,code);
            try{
                medoc=mdao.create(medoc);
                JOptionPane.showMessageDialog(this,"Médicament créé avec succès","Succès",JOptionPane.INFORMATION_MESSAGE);
            }catch(SQLException e){
                File erreur = new File("C:\\Users\\jerom\\OneDrive\\Documents\\NetBeansProjects\\Urbain_projet_medecin\\build\\classes\\swing/windows_error.wav");
                PlaySound(erreur);                
                JOptionPane.showMessageDialog(this,e,"Erreur",JOptionPane.INFORMATION_MESSAGE);
                
                
                
            }
            f.setContentPane(new menumedoc());
            f.repaint();
            f.revalidate();
    }//GEN-LAST:event_btValiderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnnuler;
    private javax.swing.JButton btValider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextArea txtaDesc;
    // End of variables declaration//GEN-END:variables
}
