/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;
import medecin.metier.Infos;
import medecin.metier.Prescription;
import medecin.metier.Medicament;
import classe.DAO.InfosDAO;
import classe.DAO.PrescriptionDAO;
import classe.DAO.MedicamentDAO;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import myconnections.DBConnection;
import swing.Creapres;
import static swing.windows.f;

/**
 *
 * @author jerom
 */
public class Infopres extends javax.swing.JPanel {

    /**
     * Creates new form Infopres
     */
    Statement stmt;
    ResultSet rs = null;
    int id,idmedoc,idpres,quantite,idmed,idpat;
    String unite,datepres,nommed;
    Prescription pres;
    Infos info;
    
    
    

    
    public Infopres(int param) {
        initComponents();
        idpres=param;
        String s=String.valueOf(idpres);
        lblPres.setText("Prescription "+s);
        spinQuantite.setValue(1);
    }
    int cpt=1;
    boolean flag;
    InfosDAO idao = new InfosDAO();
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lblPres = new javax.swing.JLabel();
        lblMedoc = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMedoc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtUnite = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        spinQuantite = new javax.swing.JSpinner();
        btPres = new javax.swing.JButton();
        btTerminer = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setBackground(new java.awt.Color(255, 204, 102));
        setLayout(new java.awt.GridLayout(5, 2, 10, 20));

        lblPres.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        add(lblPres);

        lblMedoc.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblMedoc.setText("Médicament 1");
        add(lblMedoc);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Nom du médicament");
        add(jLabel3);

        txtMedoc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtMedoc);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Unité");
        add(jLabel4);

        txtUnite.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtUnite);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Quantité");
        add(jLabel5);

        spinQuantite.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        add(spinQuantite);

        btPres.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btPres.setText("Ajouter à la prescription");
        btPres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPresActionPerformed(evt);
            }
        });
        add(btPres);

        btTerminer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btTerminer.setText("Terminer");
        btTerminer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTerminerActionPerformed(evt);
            }
        });
        add(btTerminer);
    }// </editor-fold>//GEN-END:initComponents

    private void btPresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPresActionPerformed
        try {
            Connection dbConnect = DBConnection.getConnection();
            flag=false;
            nommed=txtMedoc.getText();
            stmt = dbConnect.createStatement();
            rs = stmt.executeQuery("select * from medicament");
            while(rs.next()){
                if(rs.getString("NOM").equals(nommed)){
                    idmedoc=rs.getInt("IDMEDOC");
                    flag=true;
                }
            }
            if(flag==true){
                unite=txtUnite.getText();
                quantite= (int) spinQuantite.getValue();
                id=0;
                info= new Infos(id,idpres,idmedoc,quantite,unite);
                try{
                    info=idao.create(info);
                    cpt++;
                    String scpt=String.valueOf(cpt);
                    lblMedoc.setText("Médicament "+scpt);
                }catch(SQLException e){
                    if(e.getMessage().contains("00933")){
                        cpt++;
                        String scpt=String.valueOf(cpt);
                        lblMedoc.setText("Médicament "+scpt);
                    }else{
                    JOptionPane.showMessageDialog(this,e,"Erreur",JOptionPane.INFORMATION_MESSAGE);
                    }
                }                
            }else{
                JOptionPane.showMessageDialog(this,"Ce médicament n'existe pas","Erreur",JOptionPane.INFORMATION_MESSAGE);
            }                        
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,e,"Erreur",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btPresActionPerformed

    private void btTerminerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTerminerActionPerformed
        if(cpt==1){
            JOptionPane.showMessageDialog(this,"Entrez au moins un médicament","Erreur",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            f.setContentPane(new menupres());
            f.repaint();
            f.revalidate();
        }
    }//GEN-LAST:event_btTerminerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPres;
    private javax.swing.JButton btTerminer;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblMedoc;
    private javax.swing.JLabel lblPres;
    private javax.swing.JSpinner spinQuantite;
    private javax.swing.JTextField txtMedoc;
    private javax.swing.JTextField txtUnite;
    // End of variables declaration//GEN-END:variables
}
