/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import static swing.windows.f;

/**
 *
 * @author jerom
 */
public class menu extends javax.swing.JPanel {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btMedoc = new javax.swing.JButton();
        btMed = new javax.swing.JButton();
        btPat = new javax.swing.JButton();
        btPres = new javax.swing.JButton();
        btQuitter = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 153));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setLayout(new java.awt.GridLayout(6, 1, 0, 15));

        jLabel1.setFont(new java.awt.Font("Elephant", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu principal");
        add(jLabel1);

        btMedoc.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btMedoc.setText("Medicaments");
        btMedoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMedocActionPerformed(evt);
            }
        });
        add(btMedoc);

        btMed.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btMed.setText("Medecins");
        btMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMedActionPerformed(evt);
            }
        });
        add(btMed);

        btPat.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btPat.setText("Patients");
        btPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPatActionPerformed(evt);
            }
        });
        add(btPat);

        btPres.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btPres.setText("Prescription");
        btPres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPresActionPerformed(evt);
            }
        });
        add(btPres);

        btQuitter.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btQuitter.setText("Quitter");
        btQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuitterActionPerformed(evt);
            }
        });
        add(btQuitter);
    }// </editor-fold>//GEN-END:initComponents

    private void btMedocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMedocActionPerformed
        f.setContentPane(new menumedoc());
        f.repaint();
        f.revalidate();
        f.setSize(550,450);
    }//GEN-LAST:event_btMedocActionPerformed

    private void btMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMedActionPerformed
        f.setContentPane(new menumed());
        f.repaint();
        f.revalidate();
        f.setSize(550,450);
    }//GEN-LAST:event_btMedActionPerformed

    private void btPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPatActionPerformed
        f.setContentPane(new menupat());
        f.repaint();
        f.revalidate();
        f.setSize(550,450);
    }//GEN-LAST:event_btPatActionPerformed

    private void btQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuitterActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btQuitterActionPerformed

    private void btPresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPresActionPerformed
        f.setContentPane(new menupres());
        f.repaint();
        f.revalidate();
        f.setSize(550,450);
    }//GEN-LAST:event_btPresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btMed;
    private javax.swing.JButton btMedoc;
    private javax.swing.JButton btPat;
    private javax.swing.JButton btPres;
    private javax.swing.JButton btQuitter;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
