/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import static swing.windows.f;

/**
 *
 * @author jerom
 */
public class menupres extends javax.swing.JPanel {

    /**
     * Creates new form menupres
     */
    public menupres() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btCrea = new javax.swing.JButton();
        btAffiche = new javax.swing.JButton();
        btAffiche2 = new javax.swing.JButton();
        btModif = new javax.swing.JButton();
        btSuppr = new javax.swing.JButton();
        btRetour = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 102));
        setLayout(new java.awt.GridLayout(7, 1, 0, 10));

        jLabel1.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu prescriptions");
        add(jLabel1);

        btCrea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btCrea.setText("Effectuer une prescription");
        btCrea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCreaActionPerformed(evt);
            }
        });
        add(btCrea);

        btAffiche.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btAffiche.setText("Afficher les prescriptions d'un patient");
        btAffiche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAfficheActionPerformed(evt);
            }
        });
        add(btAffiche);

        btAffiche2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btAffiche2.setText("Afficher les prescription rédigées d'un médecin");
        btAffiche2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAffiche2ActionPerformed(evt);
            }
        });
        add(btAffiche2);

        btModif.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btModif.setText("Modifier les informations d'un prescription");
        btModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModifActionPerformed(evt);
            }
        });
        add(btModif);

        btSuppr.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btSuppr.setText("Supprimer une description");
        btSuppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSupprActionPerformed(evt);
            }
        });
        add(btSuppr);

        btRetour.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btRetour.setText("Retour");
        btRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetourActionPerformed(evt);
            }
        });
        add(btRetour);
    }// </editor-fold>//GEN-END:initComponents

    private void btRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetourActionPerformed
        f.setContentPane(new menu());
        f.repaint();
        f.revalidate();
    }//GEN-LAST:event_btRetourActionPerformed

    private void btCreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCreaActionPerformed
        f.setContentPane(new Creapres());
        f.repaint();
        f.revalidate();
    }//GEN-LAST:event_btCreaActionPerformed

    private void btAfficheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAfficheActionPerformed
        f.setContentPane(new Prespat());
        f.repaint();
        f.revalidate();
    }//GEN-LAST:event_btAfficheActionPerformed

    private void btAffiche2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAffiche2ActionPerformed
        f.setContentPane(new Presmed());
        f.repaint();
        f.revalidate();
    }//GEN-LAST:event_btAffiche2ActionPerformed

    private void btModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModifActionPerformed
        f.setContentPane(new Modifpres());
        f.repaint();
        f.revalidate();
    }//GEN-LAST:event_btModifActionPerformed

    private void btSupprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSupprActionPerformed
        f.setContentPane(new Supprpres());
        f.repaint();
        f.revalidate();
    }//GEN-LAST:event_btSupprActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAffiche;
    private javax.swing.JButton btAffiche2;
    private javax.swing.JButton btCrea;
    private javax.swing.JButton btModif;
    private javax.swing.JButton btRetour;
    private javax.swing.JButton btSuppr;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
