/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import static swing.windows.f;

/**
 *
 * @author jerom
 */
public class menumed extends javax.swing.JPanel {

    /**
     * Creates new form menumed
     */
    public menumed() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btCrea = new javax.swing.JButton();
        btAffiche = new javax.swing.JButton();
        btModif = new javax.swing.JButton();
        btSuppr = new javax.swing.JButton();
        btRetour = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new java.awt.GridLayout(6, 1, 20, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu Médecin");
        add(jLabel1);

        btCrea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btCrea.setText("Ajouter");
        btCrea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCreaActionPerformed(evt);
            }
        });
        add(btCrea);

        btAffiche.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btAffiche.setText("Afficher");
        btAffiche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAfficheActionPerformed(evt);
            }
        });
        add(btAffiche);

        btModif.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btModif.setText("Modifier");
        btModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModifActionPerformed(evt);
            }
        });
        add(btModif);

        btSuppr.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btSuppr.setText("Supprimer");
        btSuppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSupprActionPerformed(evt);
            }
        });
        add(btSuppr);

        btRetour.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btRetour.setText("Retour");
        btRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetourActionPerformed(evt);
            }
        });
        add(btRetour);
    }// </editor-fold>//GEN-END:initComponents

    private void btRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetourActionPerformed
        f.setContentPane(new menu());
        f.repaint();
        f.revalidate();
    }//GEN-LAST:event_btRetourActionPerformed

    private void btCreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCreaActionPerformed
        f.setContentPane(new Creamed());
        f.repaint();
        f.revalidate();
        f.setSize(550,450);
    }//GEN-LAST:event_btCreaActionPerformed

    private void btAfficheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAfficheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAfficheActionPerformed

    private void btModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModifActionPerformed
        f.setContentPane(new Modifmed());
        f.repaint();
        f.revalidate();
        f.setSize(550,450);
    }//GEN-LAST:event_btModifActionPerformed

    private void btSupprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSupprActionPerformed
        f.setContentPane(new Supprmed());
        f.repaint();
        f.revalidate();
        f.setSize(550,450);
    }//GEN-LAST:event_btSupprActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAffiche;
    private javax.swing.JButton btCrea;
    private javax.swing.JButton btModif;
    private javax.swing.JButton btRetour;
    private javax.swing.JButton btSuppr;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
