/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import static swing.windows.f;
import java.sql.*;
import medecin.metier.Patient;
import classe.DAO.PatientDAO;
import javax.swing.JOptionPane;
import myconnections.DBConnection;

/**
 *
 * @author jerom
 */
public class menupat extends javax.swing.JPanel {

    /**
     * Creates new form menupat
     */
    String nom,prenom,tel = "";
    Statement stmt;
    ResultSet rs = null;
    Patient pat;
    int id;
    public menupat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btCrea = new javax.swing.JButton();
        btAffiche = new javax.swing.JButton();
        btModif = new javax.swing.JButton();
        btSuppr = new javax.swing.JButton();
        btRech = new javax.swing.JButton();
        btRetour = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));
        setLayout(new java.awt.GridLayout(4, 2, 20, 20));

        jLabel1.setFont(new java.awt.Font("Elephant", 1, 28)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu patient");
        add(jLabel1);
        add(jLabel2);

        btCrea.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btCrea.setText("Ajouter");
        btCrea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCreaActionPerformed(evt);
            }
        });
        add(btCrea);

        btAffiche.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btAffiche.setText("Afficher");
        btAffiche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAfficheActionPerformed(evt);
            }
        });
        add(btAffiche);

        btModif.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btModif.setText("Modifier");
        btModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModifActionPerformed(evt);
            }
        });
        add(btModif);

        btSuppr.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btSuppr.setText("Supprimer");
        btSuppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSupprActionPerformed(evt);
            }
        });
        add(btSuppr);

        btRech.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        btRech.setText("Recherche sur le nom");
        btRech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRechActionPerformed(evt);
            }
        });
        add(btRech);

        btRetour.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btRetour.setText("Retour");
        btRetour.setMaximumSize(new java.awt.Dimension(20, 10));
        btRetour.setMinimumSize(new java.awt.Dimension(20, 10));
        btRetour.setPreferredSize(new java.awt.Dimension(20, 10));
        btRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetourActionPerformed(evt);
            }
        });
        add(btRetour);
    }// </editor-fold>//GEN-END:initComponents

    private void btRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetourActionPerformed
        f.setContentPane(new menu());
        f.repaint();
        f.revalidate();
    }//GEN-LAST:event_btRetourActionPerformed

    private void btCreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCreaActionPerformed
        f.setContentPane(new Creapat());
        f.repaint();
        f.revalidate();
        f.setSize(550,450);
    }//GEN-LAST:event_btCreaActionPerformed

    private void btModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModifActionPerformed
        f.setContentPane(new Modifpat());
        f.repaint();
        f.revalidate();
        f.setSize(550,450);
    }//GEN-LAST:event_btModifActionPerformed

    private void btSupprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSupprActionPerformed
        f.setContentPane(new Supprpat());
        f.repaint();
        f.revalidate();
        f.setSize(550,450);
    }//GEN-LAST:event_btSupprActionPerformed

    private void btAfficheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAfficheActionPerformed
        try {
            Connection dbConnect = DBConnection.getConnection();
            String aff="Liste des patients : ";
            stmt = dbConnect.createStatement();
            rs = stmt.executeQuery("select * from patient");
            while(rs.next()){                
                    id=rs.getInt("IDPAT");
                    nom=rs.getString("NOM");
                    prenom = rs.getString("PRENOM");
                    tel = rs.getString("TEL");
                    aff += "\n" +" "+ id +"\t "+ nom +"\t "+ prenom +"\t "+ tel;
            }
            JOptionPane.showMessageDialog(this,aff,"Résultat",JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,e,"Erreur",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btAfficheActionPerformed

    private void btRechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRechActionPerformed
        f.setContentPane(new Rechnom());
        f.repaint();
        f.revalidate();
        f.setSize(550,450);
    }//GEN-LAST:event_btRechActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAffiche;
    private javax.swing.JButton btCrea;
    private javax.swing.JButton btModif;
    private javax.swing.JButton btRech;
    private javax.swing.JButton btRetour;
    private javax.swing.JButton btSuppr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
