/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import static swing.windows.f;
import classe.DAO.MedicamentDAO;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import medecin.metier.Medicament;
import myconnections.DBConnection;

/**
 *
 * @author jerom
 */
public class menumedoc extends javax.swing.JPanel {

    /**
     * Creates new form menumedoc
     */
    String nom, description,code = "";
    Statement stmt;
    ResultSet rs = null;
    Medicament medoc;
    int id;
    public menumedoc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMedoc = new javax.swing.JLabel();
        btCreaMedoc = new javax.swing.JButton();
        btAffMedoc = new javax.swing.JButton();
        btModifMedoc = new javax.swing.JButton();
        BtSupMedoc = new javax.swing.JButton();
        btRetour = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 153));
        setPreferredSize(new java.awt.Dimension(550, 400));

        txtMedoc.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        txtMedoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMedoc.setText("Gestion des Medicaments");

        btCreaMedoc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btCreaMedoc.setText("Ajouter");
        btCreaMedoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCreaMedocActionPerformed(evt);
            }
        });

        btAffMedoc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btAffMedoc.setText("Afficher");
        btAffMedoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAffMedocActionPerformed(evt);
            }
        });

        btModifMedoc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btModifMedoc.setText("Modifier");
        btModifMedoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModifMedocActionPerformed(evt);
            }
        });

        BtSupMedoc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtSupMedoc.setText("Supprimer");
        BtSupMedoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSupMedocActionPerformed(evt);
            }
        });

        btRetour.setText("Retour");
        btRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtMedoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btCreaMedoc, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btModifMedoc, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtSupMedoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAffMedoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(btRetour)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtMedoc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAffMedoc, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCreaMedoc, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btModifMedoc, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtSupMedoc, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRetour)
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btCreaMedocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCreaMedocActionPerformed
        f.setContentPane(new Creamedoc());
        f.repaint();
        f.revalidate();
        f.setSize(550,450);
    }//GEN-LAST:event_btCreaMedocActionPerformed

    private void btAffMedocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAffMedocActionPerformed
        Connection dbConnect = DBConnection.getConnection();
        if (dbConnect == null) {
            JOptionPane.showMessageDialog(this,"Connexion échouée","Erreur",JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btAffMedocActionPerformed

    private void btRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetourActionPerformed

        f.setContentPane(new menu());
        f.repaint();
        f.revalidate();
    }//GEN-LAST:event_btRetourActionPerformed

    private void btModifMedocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModifMedocActionPerformed
        f.setContentPane(new Modifmedoc());
        f.repaint();
        f.revalidate();
        f.setSize(550,450);
    }//GEN-LAST:event_btModifMedocActionPerformed

    private void BtSupMedocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSupMedocActionPerformed
        f.setContentPane(new Supprmedoc());
        f.repaint();
        f.revalidate();
        f.setSize(550,450);
    }//GEN-LAST:event_BtSupMedocActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtSupMedoc;
    private javax.swing.JButton btAffMedoc;
    private javax.swing.JButton btCreaMedoc;
    private javax.swing.JButton btModifMedoc;
    private javax.swing.JButton btRetour;
    private javax.swing.JLabel txtMedoc;
    // End of variables declaration//GEN-END:variables
}
