/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import medecin.metier.*;
import classe.DAO.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import myconnections.DBConnection;
import static swing.windows.f;

/**
 *
 * @author jerom
 */
public class Modifinfos extends javax.swing.JPanel {

    /**
     * Creates new form Modifinfos
     */
    String nommed,prenommed,nommedoc,description,telmed,unite = "";
    Statement stmt;
    ResultSet rs = null;
    Patient pat;
    Infos info;
    Medicament medoc;
    Medecin med;
    Prescription pres;
    int quantite,idmedoc,id,idpres;
    public Modifinfos(int param) {
        initComponents();
        idpres=param;
        
    }
    InfosDAO idao = new InfosDAO();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btAff = new javax.swing.JButton();
        txtInfo = new javax.swing.JTextField();
        btRech = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtMedoc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtUnite = new javax.swing.JTextField();
        lblQ = new javax.swing.JLabel();
        spinQuantite = new javax.swing.JSpinner();
        btValider = new javax.swing.JButton();
        btTerminer = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 102));
        setLayout(new java.awt.GridLayout(6, 2, 10, 15));

        jLabel1.setText("Entrez l'ID de l'info :");
        add(jLabel1);

        btAff.setText("Afficher médicaments");
        btAff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAffActionPerformed(evt);
            }
        });
        add(btAff);
        add(txtInfo);

        btRech.setText("Rechercher");
        btRech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRechActionPerformed(evt);
            }
        });
        add(btRech);

        jLabel2.setText("Médicament");
        add(jLabel2);
        add(txtMedoc);

        jLabel3.setText("Unité");
        add(jLabel3);
        add(txtUnite);

        lblQ.setText("Quantité");
        add(lblQ);
        add(spinQuantite);

        btValider.setText("Valider");
        btValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btValiderActionPerformed(evt);
            }
        });
        add(btValider);

        btTerminer.setText("Terminer");
        btTerminer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTerminerActionPerformed(evt);
            }
        });
        add(btTerminer);
    }// </editor-fold>//GEN-END:initComponents

    private void btRechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRechActionPerformed
        try{
            Connection dbConnect = DBConnection.getConnection();
            String ids=txtInfo.getText();
            id=Integer.parseInt(ids);
            stmt = dbConnect.createStatement();
            rs = stmt.executeQuery("select * from infos");
            while(rs.next()){
                if(rs.getInt("IDINFO")==(id)){
                    unite=rs.getString("UNITE");
                    quantite=rs.getInt("QUANTITE");
                    idmedoc=rs.getInt("IDMEDOC");
                }
            }
            stmt = dbConnect.createStatement();
            rs = stmt.executeQuery("select * from medicament");
            while(rs.next()){
                if(rs.getInt("IDMEDOC")==(idmedoc)){
                    nommedoc=rs.getString("NOM");
                }
            }
            txtMedoc.setText(nommedoc);
            txtUnite.setText(unite);
            spinQuantite.setValue(quantite);
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(this,e,"Erreur",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btRechActionPerformed

    private void btAffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAffActionPerformed
        try{
            Connection dbConnect = DBConnection.getConnection();
            String aff="Infos de cette prescription : ";
            String req = "select * from infos WHERE idpres=? ";
            try (PreparedStatement pstm = dbConnect.prepareStatement(req)){
                pstm.setInt(1, idpres);
            //rs = stmt.executeQuery("select * from INFO_PRESCRIPTION WHERE IDPRES IN (SELECT idpres FROM PRESCRIPTION WHERE idpat=?)");
                try (ResultSet rs = pstm.executeQuery()){
                    while(rs.next()){
                        id=rs.getInt("IDINFO");
                        idmedoc=rs.getInt("IDMEDOC");
                        unite=rs.getString("UNITE");
                        quantite=rs.getInt("QUANTITE");
                        aff += "\n" +" "+ id +"\t "+ idmedoc +"\t "+ unite +"\t "+ quantite;
                    }
                    JOptionPane.showMessageDialog(this,aff,"Résultat",JOptionPane.INFORMATION_MESSAGE);
                }                
            }   
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(this,e,"Erreur",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btAffActionPerformed

    private void btValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btValiderActionPerformed
        try{
            Connection dbConnect = DBConnection.getConnection();
            nommedoc=txtMedoc.getText();
            stmt = dbConnect.createStatement();
                rs = stmt.executeQuery("select * from medicament");
                while(rs.next()){
                    if(rs.getString("NOM").equals(nommedoc)){
                        idmedoc=rs.getInt("IDMEDOC");
                    }
                }
            unite=txtUnite.getText();
            quantite= (int) spinQuantite.getValue();
            info= new Infos (id,idpres,idmedoc,quantite,unite);
            try{
                info=idao.update(info);
                JOptionPane.showMessageDialog(this,"Modification effectuée avec succès","Succès",JOptionPane.INFORMATION_MESSAGE);
            }catch (SQLException e) {
            JOptionPane.showMessageDialog(this,e,"Erreur",JOptionPane.INFORMATION_MESSAGE);
        }
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(this,e,"Erreur",JOptionPane.INFORMATION_MESSAGE);
        }    
    }//GEN-LAST:event_btValiderActionPerformed

    private void btTerminerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTerminerActionPerformed
        f.setContentPane(new menupres());
        f.repaint();
        f.revalidate();
    }//GEN-LAST:event_btTerminerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAff;
    private javax.swing.JButton btRech;
    private javax.swing.JButton btTerminer;
    private javax.swing.JButton btValider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblQ;
    private javax.swing.JSpinner spinQuantite;
    private javax.swing.JTextField txtInfo;
    private javax.swing.JTextField txtMedoc;
    private javax.swing.JTextField txtUnite;
    // End of variables declaration//GEN-END:variables
}
