/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import java.sql.ResultSet;
import java.sql.Statement;
import medecin.metier.Medecin;
import static swing.windows.f;
import classe.DAO.MedecinDAO;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import myconnections.DBConnection;
import static swing.windows.f;

/**
 *
 * @author jerom
 */
public class Modifmed extends javax.swing.JPanel {

    /**
     * Creates new form Modifmed
     */
    String matricule,nom,prenom,tel = "";
    Statement stmt;
    ResultSet rs = null;
    Medecin med;
    int id;
    public Modifmed() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomRech = new javax.swing.JTextField();
        btRech = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPrenom = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        btValider = new javax.swing.JButton();
        btAnnuler = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new java.awt.GridLayout(8, 2, 20, 10));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel1.setText("Entrez le nom :");
        add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Modification de médecin");
        add(jLabel2);

        nomRech.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(nomRech);

        btRech.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btRech.setText("Rechercher");
        btRech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRechActionPerformed(evt);
            }
        });
        add(btRech);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("ID");
        add(jLabel3);

        lblID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(lblID);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Matricule");
        add(jLabel5);

        txtMat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtMat);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Nom");
        add(jLabel6);

        txtNom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtNom);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Prenom");
        add(jLabel7);

        txtPrenom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtPrenom);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("N° de téléphone");
        add(jLabel8);

        txtTel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtTel);

        btValider.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btValider.setText("Valider");
        btValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btValiderActionPerformed(evt);
            }
        });
        add(btValider);

        btAnnuler.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btAnnuler.setText("Annuler");
        btAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnnulerActionPerformed(evt);
            }
        });
        add(btAnnuler);
    }// </editor-fold>//GEN-END:initComponents

    private void btAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnnulerActionPerformed
        f.setContentPane(new menumed());
        f.repaint();
        f.revalidate();
    }//GEN-LAST:event_btAnnulerActionPerformed

    private void btRechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRechActionPerformed
        try{
            Connection dbConnect = DBConnection.getConnection();
            nom=nomRech.getText();
            stmt = dbConnect.createStatement();
            rs = stmt.executeQuery("select * from medecin");
            while(rs.next()){
                if(rs.getString("NOM").equals(nom)){
                    id=rs.getInt("IDMED");
                    matricule=rs.getString("MATRICULE");
                    prenom = rs.getString("PRENOM");
                    tel = rs.getString("TEL");
                }
            }
            String sid=String.valueOf(id);
            lblID.setText(sid);
            txtMat.setText(matricule);
            txtNom.setText(nom);
            txtPrenom.setText(prenom);
            txtTel.setText(tel);
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(this,e,"Erreur",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btRechActionPerformed

    private void btValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btValiderActionPerformed
        MedecinDAO medao = new MedecinDAO();
        matricule=txtMat.getText();
        nom=txtNom.getText();
        prenom=txtPrenom.getText();
        tel=txtTel.getText();
        med = new Medecin(id,matricule,nom,prenom,tel);
        try{
                med=medao.update(med);
                JOptionPane.showMessageDialog(this,"Médecin modifié avec succès","Succès",JOptionPane.INFORMATION_MESSAGE);
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this,e,"Erreur",JOptionPane.INFORMATION_MESSAGE);
            }
        f.setContentPane(new menumed());
        f.repaint();
        f.revalidate();
    }//GEN-LAST:event_btValiderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnnuler;
    private javax.swing.JButton btRech;
    private javax.swing.JButton btValider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblID;
    private javax.swing.JTextField nomRech;
    private javax.swing.JTextField txtMat;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPrenom;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
