/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import myconnections.DBConnection;
import classe.DAO.PatientDAO;
import java.sql.ResultSet;
import java.sql.Statement;
import medecin.metier.Patient;
import static swing.windows.f;

/**
 *
 * @author jerom
 */
public class Modifpat extends javax.swing.JPanel {

    /**
     * Creates new form Modifpat
     */
    String nom,prenom,tel = "";
    Statement stmt;
    ResultSet rs = null;
    Patient pat;
    int id;
    public Modifpat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomRech = new javax.swing.JTextField();
        btRech = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPrenom = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        btValider = new javax.swing.JButton();
        BtAnnuler = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));
        setLayout(new java.awt.GridLayout(7, 2, 20, 10));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel1.setText("Entrez l'ID du patient :");
        add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Modification de patient");
        add(jLabel2);

        nomRech.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nomRech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomRechActionPerformed(evt);
            }
        });
        add(nomRech);

        btRech.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btRech.setText("Rechercher");
        btRech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRechActionPerformed(evt);
            }
        });
        add(btRech);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("ID");
        add(jLabel4);

        lblID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(lblID);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Nom");
        add(jLabel5);

        txtNom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtNom);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Prenom");
        add(jLabel6);

        txtPrenom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtPrenom);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("N° de téléhpone");
        add(jLabel7);

        txtTel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtTel);

        btValider.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btValider.setText("Valider");
        btValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btValiderActionPerformed(evt);
            }
        });
        add(btValider);

        BtAnnuler.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtAnnuler.setText("Annuler");
        BtAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAnnulerActionPerformed(evt);
            }
        });
        add(BtAnnuler);
    }// </editor-fold>//GEN-END:initComponents

    private void nomRechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomRechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomRechActionPerformed

    private void btRechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRechActionPerformed
        try{
            Connection dbConnect = DBConnection.getConnection();
            String ids=nomRech.getText();
            id=Integer.parseInt(ids);
            stmt = dbConnect.createStatement();
            rs = stmt.executeQuery("select * from patient");
            while(rs.next()){
                if(rs.getInt("IDPAT")==(id)){
                    nom=rs.getString("NOM");
                    prenom = rs.getString("PRENOM");
                    tel = rs.getString("TEL");
                }
            }
            String sid=String.valueOf(id);
            lblID.setText(sid);
            txtNom.setText(nom);
            txtPrenom.setText(prenom);
            txtTel.setText(tel);
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(this,e,"Erreur",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btRechActionPerformed

    private void btValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btValiderActionPerformed
        PatientDAO pdao = new PatientDAO();        
        nom=txtNom.getText();
        prenom=txtPrenom.getText();
        tel=txtTel.getText();
        pat= new Patient(id,nom,prenom,tel);
        try{
            pat=pdao.update(pat);
            JOptionPane.showMessageDialog(this,"Patient modifié avec succès","Succès",JOptionPane.INFORMATION_MESSAGE);
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this,e,"Erreur",JOptionPane.INFORMATION_MESSAGE);
            }
        f.setContentPane(new menupat());
        f.repaint();
        f.revalidate();
    }//GEN-LAST:event_btValiderActionPerformed

    private void BtAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAnnulerActionPerformed
        f.setContentPane(new menupat());
        f.repaint();
        f.revalidate();
    }//GEN-LAST:event_BtAnnulerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAnnuler;
    private javax.swing.JButton btRech;
    private javax.swing.JButton btValider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblID;
    private javax.swing.JTextField nomRech;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPrenom;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
