/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;
import static swing.windows.f;
import classe.DAO.MedicamentDAO;
import static classe.DAO.MedicamentDAO.plusieurs2;
import medecin.metier.Medicament;
import myconnections.DBConnection;
import java.sql.*;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jerom
 */
public class Rechdesc extends javax.swing.JPanel {

    /**
     * Creates new form RechDesc
     */
    String nom,desc,code = "";
    Statement stmt;
    ResultSet rs = null;
    Medicament medoc;
    int id;
    public Rechdesc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRech = new javax.swing.JTextField();
        btRech = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btRetour = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 153));
        setLayout(new java.awt.GridLayout(3, 2, 20, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel1.setText("Entrez le mot clé :");
        add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel2.setText("Recherche Description");
        add(jLabel2);

        txtRech.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtRech);

        btRech.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btRech.setText("Rechercher");
        btRech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRechActionPerformed(evt);
            }
        });
        add(btRech);
        add(jLabel3);

        btRetour.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btRetour.setText("Retour");
        btRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetourActionPerformed(evt);
            }
        });
        add(btRetour);
    }// </editor-fold>//GEN-END:initComponents

    private void btRechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRechActionPerformed
        
        Connection dbConnect = DBConnection.getConnection();
        String description=txtRech.getText();
        try {
            MedicamentDAO mdao = new MedicamentDAO();
            mdao.rechDesc(description);
            JOptionPane.showMessageDialog(this,MedicamentDAO.plusieurs2,"Résultat",JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,e,"Erreur",JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btRechActionPerformed

    private void btRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetourActionPerformed
        f.setContentPane(new menumedoc());
        f.repaint();
        f.revalidate();
    }//GEN-LAST:event_btRetourActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRech;
    private javax.swing.JButton btRetour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtRech;
    // End of variables declaration//GEN-END:variables
}
