/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import myconnections.DBConnection;
import classe.DAO.PatientDAO;
import java.sql.ResultSet;
import java.sql.Statement;
import medecin.metier.Patient;
import static swing.windows.f;


/**
 *
 * @author jerom
 */
public class Rechnom extends javax.swing.JPanel {

    /**
     * Creates new form Rechnom
     */
    String nom,prenom,tel = "";
    Statement stmt;
    ResultSet rs = null;
    Patient pat;
    int id;
    public Rechnom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        btRech = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btAnnuler = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));
        setLayout(new java.awt.GridLayout(3, 2, 20, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel1.setText("Entrez le nom :");
        add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Recherche nom");
        add(jLabel2);

        txtNom.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        add(txtNom);

        btRech.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btRech.setText("Rechercher");
        btRech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRechActionPerformed(evt);
            }
        });
        add(btRech);
        add(jLabel3);

        btAnnuler.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btAnnuler.setText("Annuler");
        btAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnnulerActionPerformed(evt);
            }
        });
        add(btAnnuler);
    }// </editor-fold>//GEN-END:initComponents

    private void btRechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRechActionPerformed
        try{
            Connection dbConnect = DBConnection.getConnection();
            String aff="";
            nom=txtNom.getText();
            stmt = dbConnect.createStatement();
            rs = stmt.executeQuery("select * from patient");
            while(rs.next()){
                if(rs.getString("NOM").equals(nom)){
                    id=rs.getInt("IDPAT");
                    prenom = rs.getString("PRENOM");
                    tel = rs.getString("TEL");
                    aff += "\n" +" "+ id +"\t "+ nom +"\t "+ prenom +"\t "+ tel;
                }
            }
            JOptionPane.showMessageDialog(this,aff,"Résultat",JOptionPane.INFORMATION_MESSAGE);
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(this,e,"Erreur",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btRechActionPerformed

    private void btAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnnulerActionPerformed
        f.setContentPane(new menupat());
        f.repaint();
        f.revalidate();
    }//GEN-LAST:event_btAnnulerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnnuler;
    private javax.swing.JButton btRech;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtNom;
    // End of variables declaration//GEN-END:variables
}
