/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import java.sql.ResultSet;
import java.sql.Statement;
import medecin.metier.Medecin;
import static swing.windows.f;
import classe.DAO.MedecinDAO;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import myconnections.DBConnection;
import static swing.windows.f;

/**
 *
 * @author jerom
 */
public class Supprmed extends javax.swing.JPanel {

    /**
     * Creates new form Supprmed
     */
    String matricule,nom,prenom,tel = "";
    Statement stmt;
    ResultSet rs = null;
    Medecin med;
    int id;
    public Supprmed() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomRech = new javax.swing.JTextField();
        btRech = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblMat = new javax.swing.JLabel();
        lblTel = new javax.swing.JLabel();
        lblNom = new javax.swing.JLabel();
        lblPrenom = new javax.swing.JLabel();
        btValider = new javax.swing.JButton();
        btAnnuler = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new java.awt.GridLayout(6, 2, 20, 10));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel1.setText("Entrez le nom :");
        add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Suppression de médecin");
        add(jLabel2);

        nomRech.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(nomRech);

        btRech.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btRech.setText("Rechercher");
        btRech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRechActionPerformed(evt);
            }
        });
        add(btRech);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Infos du médecin");
        add(jLabel3);

        lblID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(lblID);

        lblMat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(lblMat);

        lblTel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(lblTel);

        lblNom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(lblNom);

        lblPrenom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(lblPrenom);

        btValider.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btValider.setText("Valider");
        btValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btValiderActionPerformed(evt);
            }
        });
        add(btValider);

        btAnnuler.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btAnnuler.setText("Annuler");
        btAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnnulerActionPerformed(evt);
            }
        });
        add(btAnnuler);
    }// </editor-fold>//GEN-END:initComponents

    private void btAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnnulerActionPerformed
        f.setContentPane(new menumed());
        f.repaint();
        f.revalidate();
    }//GEN-LAST:event_btAnnulerActionPerformed

    private void btRechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRechActionPerformed
        try{
            Connection dbConnect = DBConnection.getConnection();
            nom=nomRech.getText();
            stmt = dbConnect.createStatement();
            rs = stmt.executeQuery("select * from medecin");
            while(rs.next()){
                if(rs.getString("NOM").equals(nom)){
                    id=rs.getInt("IDMED");
                    matricule=rs.getString("MATRICULE");
                    prenom = rs.getString("PRENOM");
                    tel = rs.getString("TEL");
                }
            }
            String sid=String.valueOf(id);
            lblID.setText("ID : "+sid);
            lblMat.setText("Matricule : "+matricule);
            lblNom.setText("Nom : "+nom);
            lblPrenom.setText("Prenom : "+prenom);
            lblTel.setText("N° de téléphone : "+tel);
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(this,e,"Erreur",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btRechActionPerformed

    private void btValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btValiderActionPerformed
        MedecinDAO medao = new MedecinDAO();
        med = new Medecin(id,matricule,nom,prenom,tel);
        try{
            medao.delete(med);
            JOptionPane.showMessageDialog(this,"Médecin supprimé avec succès","Succès",JOptionPane.INFORMATION_MESSAGE);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this,e,"Erreur",JOptionPane.INFORMATION_MESSAGE);
        }
        f.setContentPane(new menumed());
        f.repaint();
        f.revalidate();
    }//GEN-LAST:event_btValiderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnnuler;
    private javax.swing.JButton btRech;
    private javax.swing.JButton btValider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMat;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblPrenom;
    private javax.swing.JLabel lblTel;
    private javax.swing.JTextField nomRech;
    // End of variables declaration//GEN-END:variables
}
