/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import static swing.windows.f;
import classe.DAO.MedicamentDAO;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import medecin.metier.Medicament;
import myconnections.DBConnection;

/**
 *
 * @author jerom
 */
public class Supprmedoc extends javax.swing.JPanel {

    /**
     * Creates new form Supprmedoc
     */
    String nom, description,code = "";
    Statement stmt;
    ResultSet rs = null;
    Medicament medoc;
    int id;
    public Supprmedoc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomRech = new javax.swing.JTextField();
        btRech = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        lblCode = new javax.swing.JLabel();
        lblNom = new javax.swing.JLabel();
        lblDesc = new javax.swing.JLabel();
        btValider = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 153));
        setLayout(new java.awt.GridLayout(5, 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel1.setText("Entrez le nom :");
        add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel2.setText("Suppresion de médicament");
        add(jLabel2);

        nomRech.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(nomRech);

        btRech.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btRech.setText("Rechercher");
        btRech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRechActionPerformed(evt);
            }
        });
        add(btRech);

        lblID.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        add(lblID);

        lblCode.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        add(lblCode);

        lblNom.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        add(lblNom);

        lblDesc.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        add(lblDesc);

        btValider.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btValider.setText("Valider");
        btValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btValiderActionPerformed(evt);
            }
        });
        add(btValider);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Annuler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        f.setContentPane(new menumedoc());
        f.repaint();
        f.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btRechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRechActionPerformed
        try {
            Connection dbConnect = DBConnection.getConnection();
            nom=nomRech.getText();
            stmt = dbConnect.createStatement();
            rs = stmt.executeQuery("select * from medicament");
            while(rs.next()){
                if(rs.getString("NOM").equals(nom)){
                    id=rs.getInt("IDMEDOC");
                    description = rs.getString("DESCRIPTION");
                    code = rs.getString("CODE");
                }
            }
            String sid=String.valueOf(id);
            lblID.setText("ID : "+sid);
            lblNom.setText("Nom : "+nom);
            lblCode.setText("Code : "+code);
            lblDesc.setText("Description : "+description);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,e,"Erreur",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btRechActionPerformed

    private void btValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btValiderActionPerformed
        MedicamentDAO mdao = new MedicamentDAO();
        medoc = new Medicament(id,nom,description,code);
        try{
            mdao.delete(medoc);
            JOptionPane.showMessageDialog(this,"Médicament supprimé avec succès","Succès",JOptionPane.INFORMATION_MESSAGE);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this,e,"Erreur",JOptionPane.INFORMATION_MESSAGE);
        }
        f.setContentPane(new menumedoc());
        f.repaint();
        f.revalidate();
    }//GEN-LAST:event_btValiderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRech;
    private javax.swing.JButton btValider;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCode;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNom;
    private javax.swing.JTextField nomRech;
    // End of variables declaration//GEN-END:variables
}
